<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CustomerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $customers = [
            // Platinum Members - VIP customers
            [
                'name' => 'Robert Anderson',
                'phone' => '+1 (213) 555-0101',
                'email' => 'robert.anderson@gmail.com',
                'plate_number' => '7ABC123',
                'vehicle_type' => 'sedan',
                'make' => 'Mercedes-Benz',
                'model' => 'S-Class',
                'color' => 'Black',
                'membership' => 'Platinum',
                'status' => 'active',
            ],
            [
                'name' => 'Jennifer Williams',
                'phone' => '+1 (310) 555-0102',
                'email' => 'jwilliams@yahoo.com',
                'plate_number' => '5XYZ789',
                'vehicle_type' => 'suv',
                'make' => 'Range Rover',
                'model' => 'Sport',
                'color' => 'White',
                'membership' => 'Platinum',
                'status' => 'active',
            ],
            [
                'name' => 'Michael Chen',
                'phone' => '+1 (818) 555-0103',
                'email' => 'mchen@outlook.com',
                'plate_number' => '8DEF456',
                'vehicle_type' => 'sedan',
                'make' => 'BMW',
                'model' => '7 Series',
                'color' => 'Silver',
                'membership' => 'Platinum',
                'status' => 'active',
            ],
            [
                'name' => 'Elizabeth Thompson',
                'phone' => '+1 (310) 555-0104',
                'email' => 'e.thompson@icloud.com',
                'plate_number' => '3GHI789',
                'vehicle_type' => 'sedan',
                'make' => 'Tesla',
                'model' => 'Model S',
                'color' => 'Red',
                'membership' => 'Platinum',
                'status' => 'active',
            ],

            // Gold Members - Regular loyal customers
            [
                'name' => 'David Martinez',
                'phone' => '+1 (323) 555-0201',
                'email' => 'dmartinez@gmail.com',
                'plate_number' => '6JKL012',
                'vehicle_type' => 'suv',
                'make' => 'Lexus',
                'model' => 'RX 350',
                'color' => 'Blue',
                'membership' => 'Gold',
                'status' => 'active',
            ],
            [
                'name' => 'Sarah Johnson',
                'phone' => '+1 (626) 555-0202',
                'email' => 'sarahj@hotmail.com',
                'plate_number' => '4MNO345',
                'vehicle_type' => 'sedan',
                'make' => 'Audi',
                'model' => 'A4',
                'color' => 'Gray',
                'membership' => 'Gold',
                'status' => 'active',
            ],
            [
                'name' => 'James Rodriguez',
                'phone' => '+1 (562) 555-0203',
                'email' => 'jrodriguez@gmail.com',
                'plate_number' => '9PQR678',
                'vehicle_type' => 'truck',
                'make' => 'Toyota',
                'model' => 'Tacoma',
                'color' => 'Green',
                'membership' => 'Gold',
                'status' => 'active',
            ],
            [
                'name' => 'Maria Garcia',
                'phone' => '+1 (213) 555-0204',
                'email' => 'mgarcia@yahoo.com',
                'plate_number' => '2STU901',
                'vehicle_type' => 'suv',
                'make' => 'Honda',
                'model' => 'Pilot',
                'color' => 'White',
                'membership' => 'Gold',
                'status' => 'active',
            ],
            [
                'name' => 'Christopher Lee',
                'phone' => '+1 (818) 555-0205',
                'email' => 'clee@outlook.com',
                'plate_number' => '1VWX234',
                'vehicle_type' => 'sedan',
                'make' => 'Acura',
                'model' => 'TLX',
                'color' => 'Black',
                'membership' => 'Gold',
                'status' => 'active',
            ],

            // Silver Members - Occasional customers
            [
                'name' => 'Jessica Brown',
                'phone' => '+1 (310) 555-0301',
                'email' => 'jbrown@gmail.com',
                'plate_number' => '7YZA567',
                'vehicle_type' => 'sedan',
                'make' => 'Toyota',
                'model' => 'Camry',
                'color' => 'Silver',
                'membership' => 'Silver',
                'status' => 'active',
            ],
            [
                'name' => 'Daniel Kim',
                'phone' => '+1 (323) 555-0302',
                'email' => 'dkim@yahoo.com',
                'plate_number' => '5BCD890',
                'vehicle_type' => 'suv',
                'make' => 'Nissan',
                'model' => 'Rogue',
                'color' => 'Blue',
                'membership' => 'Silver',
                'status' => 'active',
            ],
            [
                'name' => 'Amanda Wilson',
                'phone' => '+1 (626) 555-0303',
                'email' => 'awilson@hotmail.com',
                'plate_number' => '3EFG123',
                'vehicle_type' => 'sedan',
                'make' => 'Honda',
                'model' => 'Accord',
                'color' => 'Red',
                'membership' => 'Silver',
                'status' => 'active',
            ],
            [
                'name' => 'Thomas Davis',
                'phone' => '+1 (562) 555-0304',
                'email' => 'tdavis@gmail.com',
                'plate_number' => '8HIJ456',
                'vehicle_type' => 'truck',
                'make' => 'Ford',
                'model' => 'F-150',
                'color' => 'Gray',
                'membership' => 'Silver',
                'status' => 'active',
            ],
            [
                'name' => 'Michelle Taylor',
                'phone' => '+1 (213) 555-0305',
                'email' => null,
                'plate_number' => '6KLM789',
                'vehicle_type' => 'suv',
                'make' => 'Mazda',
                'model' => 'CX-5',
                'color' => 'White',
                'membership' => 'Silver',
                'status' => 'active',
            ],

            // Regular Members - New or walk-in customers
            [
                'name' => 'Kevin Nguyen',
                'phone' => '+1 (818) 555-0401',
                'email' => 'knguyen@outlook.com',
                'plate_number' => '4NOP012',
                'vehicle_type' => 'sedan',
                'make' => 'Hyundai',
                'model' => 'Sonata',
                'color' => 'Black',
                'membership' => 'Regular',
                'status' => 'active',
            ],
            [
                'name' => 'Nicole White',
                'phone' => '+1 (310) 555-0402',
                'email' => 'nwhite@gmail.com',
                'plate_number' => '2QRS345',
                'vehicle_type' => 'sedan',
                'make' => 'Kia',
                'model' => 'Optima',
                'color' => 'Blue',
                'membership' => 'Regular',
                'status' => 'active',
            ],
            [
                'name' => 'Brian Jackson',
                'phone' => '+1 (323) 555-0403',
                'email' => null,
                'plate_number' => '9TUV678',
                'vehicle_type' => 'van',
                'make' => 'Chrysler',
                'model' => 'Pacifica',
                'color' => 'Silver',
                'membership' => 'Regular',
                'status' => 'active',
            ],
            [
                'name' => 'Rachel Harris',
                'phone' => '+1 (626) 555-0404',
                'email' => 'rharris@yahoo.com',
                'plate_number' => '7WXY901',
                'vehicle_type' => 'suv',
                'make' => 'Jeep',
                'model' => 'Grand Cherokee',
                'color' => 'Green',
                'membership' => 'Regular',
                'status' => 'active',
            ],
            [
                'name' => 'Steven Clark',
                'phone' => '+1 (562) 555-0405',
                'email' => 'sclark@gmail.com',
                'plate_number' => '5ZAB234',
                'vehicle_type' => 'sedan',
                'make' => 'Volkswagen',
                'model' => 'Jetta',
                'color' => 'White',
                'membership' => 'Regular',
                'status' => 'active',
            ],
            [
                'name' => 'Patricia Lopez',
                'phone' => '+1 (213) 555-0406',
                'email' => null,
                'plate_number' => '3CDE567',
                'vehicle_type' => 'sedan',
                'make' => 'Chevrolet',
                'model' => 'Malibu',
                'color' => 'Gray',
                'membership' => 'Regular',
                'status' => 'active',
            ],
            [
                'name' => 'Andrew Martin',
                'phone' => '+1 (818) 555-0407',
                'email' => 'amartin@hotmail.com',
                'plate_number' => '1FGH890',
                'vehicle_type' => 'truck',
                'make' => 'GMC',
                'model' => 'Sierra',
                'color' => 'Black',
                'membership' => 'Regular',
                'status' => 'active',
            ],
            [
                'name' => 'Laura Moore',
                'phone' => '+1 (310) 555-0408',
                'email' => 'lmoore@icloud.com',
                'plate_number' => '8IJK123',
                'vehicle_type' => 'sedan',
                'make' => 'Subaru',
                'model' => 'Legacy',
                'color' => 'Blue',
                'membership' => 'Regular',
                'status' => 'active',
            ],
            [
                'name' => 'Mark Thompson',
                'phone' => '+1 (323) 555-0409',
                'email' => null,
                'plate_number' => '6LMN456',
                'vehicle_type' => 'suv',
                'make' => 'Ford',
                'model' => 'Explorer',
                'color' => 'Red',
                'membership' => 'Regular',
                'status' => 'active',
            ],
            [
                'name' => 'Karen Robinson',
                'phone' => '+1 (626) 555-0410',
                'email' => 'krobinson@gmail.com',
                'plate_number' => '4OPQ789',
                'vehicle_type' => 'sedan',
                'make' => 'Nissan',
                'model' => 'Altima',
                'color' => 'White',
                'membership' => 'Regular',
                'status' => 'active',
            ],

            // Special Vehicles
            [
                'name' => 'Richard Walker',
                'phone' => '+1 (562) 555-0501',
                'email' => 'rwalker@yahoo.com',
                'plate_number' => '2RST012',
                'vehicle_type' => 'motorcycle',
                'make' => 'Harley-Davidson',
                'model' => 'Road King',
                'color' => 'Black',
                'membership' => 'Regular',
                'status' => 'active',
            ],
            [
                'name' => 'Sandra Young',
                'phone' => '+1 (213) 555-0502',
                'email' => 'syoung@outlook.com',
                'plate_number' => '9UVW345',
                'vehicle_type' => 'sedan',
                'make' => 'Porsche',
                'model' => 'Panamera',
                'color' => 'Silver',
                'membership' => 'Platinum',
                'status' => 'active',
            ],
            [
                'name' => 'Gary Allen',
                'phone' => '+1 (818) 555-0503',
                'email' => null,
                'plate_number' => '7XYZ678',
                'vehicle_type' => 'truck',
                'make' => 'Ram',
                'model' => '1500',
                'color' => 'Blue',
                'membership' => 'Silver',
                'status' => 'active',
            ],
            [
                'name' => 'Nancy Hill',
                'phone' => '+1 (310) 555-0504',
                'email' => 'nhill@gmail.com',
                'plate_number' => '5ABC901',
                'vehicle_type' => 'van',
                'make' => 'Honda',
                'model' => 'Odyssey',
                'color' => 'Gray',
                'membership' => 'Gold',
                'status' => 'active',
            ],

            // Inactive Customer
            [
                'name' => 'Paul Scott',
                'phone' => '+1 (323) 555-0601',
                'email' => 'pscott@hotmail.com',
                'plate_number' => '3DEF234',
                'vehicle_type' => 'sedan',
                'make' => 'Dodge',
                'model' => 'Charger',
                'color' => 'Black',
                'membership' => 'Regular',
                'status' => 'inactive',
            ],
        ];

        foreach ($customers as $customer) {
            \App\Models\Customer::create($customer);
        }
    }
}
